#!/usr/bin/env bash

# Build a temp file string for use with the configuration
export CONFIG=$(mktemp /tmp/abc-script.XXXXXX)

# Put contents of the config file in between the EOL markers.
# NOTE: Be mindful of the commas this is JSON (except for the comments)
#       not python.  Trailing ',' are an error.
cat > $CONFIG <<EOL
{
    "schedule_publish_interval": 30,
    "heartbeat_interval": 20,
    "preempt_grace_time": 30
}
EOL

export CONFIG=services/core/VolttronCentral/config
export TAG=vc
export SOURCE=services/core/VolttronCentral
export AGENT_VIP_IDENTITY=volttron.central

./scripts/core/upgrade-agent.sh
#python ./scripts/install-agent.py -s $SOURCE -c $CONFIG -i $AGENT_VIP_IDENTITY --force --start

# To set the agent to autostart with the platform, pass "enable"
# to upgrade-agent.sh: ./scripts/core/upgrade-agent.sh enable
