#!/usr/bin/env bash

# Build a temp file string for use with the configuration
export CONFIG=$(mktemp /tmp/abc-script.XXXXXX)

# Put contents of the config file in between the EOL markers.
# NOTE: Be mindful of the commas this is JSON (except for the comments)
#       not python.  Trailing ',' are an error.
cat > $CONFIG <<EOL
{
    "device_group": {
        "devices/fake-campus/fake-building/fake-device/all": {
            "seconds": 10,
            "points": ["temperature", "PowerState"]
        }
    }
}
EOL

export SOURCE=services/core/MasterDriverAgent/
export TAG=master-driver

# Upgrade requires that the identity be set to upgrade the agent.
# NOTE: if the agent doesn't exist it will be installed.

# Add NO_START parameter if the agent shouldn't start
# export NO_START=1

./scripts/core/upgrade-agent.sh
#python ./scripts/install-agent.py -s $SOURCE --start

# To set the agent to autostart with the platform, pass "enable" 
# to make-agent.sh: ./scripts/core/make-agent.sh enable

# Finally remove the temporary config file
rm $CONFIG

