#!/usr/bin/env bash

# Build a temp file string for use with the configuration
export CONFIG=$(mktemp /tmp/abc-script.XXXXXX)

# Put contents of the config file in between the EOL markers.
# NOTE: Be mindful of the commas this is JSON (except for the comments)
#       not python.  Trailing ',' are an error.
cat > $CONFIG <<EOL
{
    "agent": {
        "exec": "schedule_exampleagent-0.1-py2.7.egg --config \"%c\" --sub \"%s\" --pub \"%p\""
    },
    "agentid": "schedule_example",
    "message": "hello"
}
EOL

export SOURCE=examples/SchedulerExample/
export TAG=scheduler

# Upgrade requires that the identity be set to upgrade the agent.
# NOTE: if the agent doesn't exist it will be installed.
export AGENT_VIP_IDENTITY="SchedulerAgent"

# Add NO_START parameter if the agent shouldn't start
# export NO_START=1

./scripts/core/upgrade-agent.sh

# To set the agent to autostart with the platform, pass "enable" 
# to make-agent.sh: ./scripts/core/make-agent.sh enable


# Finally remove the temporary config file
rm $CONFIG
