#LSTM encoder model path
encoder_model_path: /home/niddodi/git/volttron/examples/TensorflowBuildingModelAgent/data/s2s_encoder_Building1/1/
#LSTM decoder model path
decoder_model_path: /home/niddodi/git/volttron/examples/TensorflowBuildingModelAgent/data/s2s_decoder_Building1/1
#Raw building power and outdoor air temperature dataset
building_data_path: /home/niddodi/git/volttron/examples/TensorflowBuildingModelAgent/data/LSTM_Building1_New_5min.csv
